[project]
name = "people-pairer"
version = "1.0.0"
description = "Simple software to produce pairs from a given list of participants, ensuring that people in the same team are not paired, and that pairs are not repeated from previous rounds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
]
